# Generated by Django 5.0.6 on 2024-06-06 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('engine_number', models.CharField(max_length=255)),
                ('transmission_number', models.CharField(max_length=255)),
                ('drive_axle_number', models.CharField(max_length=255)),
                ('steer_axle_number', models.CharField(max_length=255)),
                ('supply_date', models.DateField()),
                ('client', models.CharField(max_length=255)),
                ('end_user', models.CharField(max_length=255)),
                ('delivery_address', models.TextField()),
                ('additional_options', models.TextField()),
                ('service_company', models.CharField(max_length=255)),
                ('drive_axle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines_as_drive_axle_model', to='myapp.dictionary')),
                ('engine_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines_as_engine_model', to='myapp.dictionary')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines_as_model', to='myapp.dictionary')),
                ('steer_axle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines_as_steer_axle_model', to='myapp.dictionary')),
                ('transmission_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines_as_transmission_model', to='myapp.dictionary')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_date', models.DateField(verbose_name='Дата отказа')),
                ('operating_hours', models.IntegerField(verbose_name='Наработка, м/час')),
                ('failure_description', models.TextField(verbose_name='Описание отказа')),
                ('parts_used', models.TextField(verbose_name='Используемые запасные части')),
                ('recovery_date', models.DateField(verbose_name='Дата восстановления')),
                ('downtime', models.IntegerField(editable=False, verbose_name='Время простоя техники')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_as_service_company', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания')),
                ('failure_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_as_failure_node', to='myapp.dictionary', verbose_name='Узел отказа')),
                ('recovery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_as_recovery_method', to='myapp.dictionary', verbose_name='Способ восстановления')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='myapp.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField()),
                ('runtime_hours', models.IntegerField()),
                ('order_number', models.CharField(max_length=100)),
                ('order_date', models.DateField()),
                ('maintenance_organization', models.CharField(max_length=255)),
                ('operating_hours', models.IntegerField()),
                ('downtime', models.IntegerField()),
                ('recovery_method', models.TextField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances_as_machine', to='myapp.machine')),
                ('maintenance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances_as_type', to='myapp.dictionary')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances_as_organization', to='myapp.dictionary')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances_as_service_company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
