# Generated by Django 5.0.6 on 2024-06-06 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='downtime',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='failure_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='failure_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_as_failure_node', to='myapp.dictionary'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='operating_hours',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='parts_used',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='recovery_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='recovery_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_as_recovery_method', to='myapp.dictionary'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_as_service_company', to=settings.AUTH_USER_MODEL),
        ),
    ]
